create table "public"."clients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_name" bigint not null,
    "active" boolean not null,
    "address" bigint not null,
    "abn" bigint not null,
    "email" bigint not null,
    "signer_names" bigint[]
);


alter table "public"."clients" enable row level security;

create table "public"."employees" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" bigint,
    "type" bigint
);


alter table "public"."employees" enable row level security;

create table "public"."pickups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "employeeId" bigint not null,
    "clientId" bigint not null,
    "tyres" json
);


alter table "public"."pickups" enable row level security;

CREATE UNIQUE INDEX clients_abn_key ON public.clients USING btree (abn);

CREATE UNIQUE INDEX clients_active_key ON public.clients USING btree (active);

CREATE UNIQUE INDEX clients_business_name_key ON public.clients USING btree (business_name);

CREATE UNIQUE INDEX clients_email_key ON public.clients USING btree (email);

CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree (id);

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

CREATE UNIQUE INDEX pickups_pkey ON public.pickups USING btree (id);

alter table "public"."clients" add constraint "clients_pkey" PRIMARY KEY using index "clients_pkey";

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";

alter table "public"."pickups" add constraint "pickups_pkey" PRIMARY KEY using index "pickups_pkey";

alter table "public"."clients" add constraint "clients_abn_key" UNIQUE using index "clients_abn_key";

alter table "public"."clients" add constraint "clients_active_key" UNIQUE using index "clients_active_key";

alter table "public"."clients" add constraint "clients_business_name_key" UNIQUE using index "clients_business_name_key";

alter table "public"."clients" add constraint "clients_email_key" UNIQUE using index "clients_email_key";

alter table "public"."pickups" add constraint "pickups_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) not valid;

alter table "public"."pickups" validate constraint "pickups_clientId_fkey";

alter table "public"."pickups" add constraint "pickups_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES employees(id) not valid;

alter table "public"."pickups" validate constraint "pickups_employeeId_fkey";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."employees" to "anon";

grant insert on table "public"."employees" to "anon";

grant references on table "public"."employees" to "anon";

grant select on table "public"."employees" to "anon";

grant trigger on table "public"."employees" to "anon";

grant truncate on table "public"."employees" to "anon";

grant update on table "public"."employees" to "anon";

grant delete on table "public"."employees" to "authenticated";

grant insert on table "public"."employees" to "authenticated";

grant references on table "public"."employees" to "authenticated";

grant select on table "public"."employees" to "authenticated";

grant trigger on table "public"."employees" to "authenticated";

grant truncate on table "public"."employees" to "authenticated";

grant update on table "public"."employees" to "authenticated";

grant delete on table "public"."employees" to "service_role";

grant insert on table "public"."employees" to "service_role";

grant references on table "public"."employees" to "service_role";

grant select on table "public"."employees" to "service_role";

grant trigger on table "public"."employees" to "service_role";

grant truncate on table "public"."employees" to "service_role";

grant update on table "public"."employees" to "service_role";

grant delete on table "public"."pickups" to "anon";

grant insert on table "public"."pickups" to "anon";

grant references on table "public"."pickups" to "anon";

grant select on table "public"."pickups" to "anon";

grant trigger on table "public"."pickups" to "anon";

grant truncate on table "public"."pickups" to "anon";

grant update on table "public"."pickups" to "anon";

grant delete on table "public"."pickups" to "authenticated";

grant insert on table "public"."pickups" to "authenticated";

grant references on table "public"."pickups" to "authenticated";

grant select on table "public"."pickups" to "authenticated";

grant trigger on table "public"."pickups" to "authenticated";

grant truncate on table "public"."pickups" to "authenticated";

grant update on table "public"."pickups" to "authenticated";

grant delete on table "public"."pickups" to "service_role";

grant insert on table "public"."pickups" to "service_role";

grant references on table "public"."pickups" to "service_role";

grant select on table "public"."pickups" to "service_role";

grant trigger on table "public"."pickups" to "service_role";

grant truncate on table "public"."pickups" to "service_role";

grant update on table "public"."pickups" to "service_role";


